### ISSUE TITLE
是否考虑桌面端可访问性

### ISSUE THREAD

**Issue by wswmsword** [wayn111/waynboot-mobile#5]
你好 wayn111，vw 适配会导致大屏大字问题，在桌面端和横屏时变得难以访问。请问是否考虑优化宽屏的移动端视图的可访问性，正好我最近写了个插件，[postcss-mobile-forever](https://github.com/wswmsword/postcss-mobile-forever)，这个插件可以限制最大宽度，同时也使用 vw 实现可伸缩的移动端视图，同时“限制宽度”这个特性也是可选的，最终是否适配桌面端的决定权在于开发者，如果不适配，使用插件表现的效果将和 px-to-viewport 一样。

如果需要的话，我可以给您提一个 PR。

**Comment by wayn111** [comment]
可以接入，感谢

**Comment by wswmsword** [comment]
#6 接入了，样式基本上能适配，不过貌似现在项目的 vue-cli 是旧的，内置的是 PostCSS 7，PostCSS 7 和 PostCSS 8 两个版本的 mobile-forever 我都写了，但如果能升级下 vue-cli，内置成 PostCSS 8 就更好了。
